name: Release

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v2
            - name: Add NodeJS
              id: addNode
              uses: actions/setup-node@v1
              with:
                  node-version: "14"
            - name: Run Prerequisites
              env:
                  GH_CLI_AUTH_TOKEN: ${{secrets.GH_CLI_AUTH_TOKEN}}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
              id: runPrerequisites
              run: |
                  npm i -g vsce
                  git config --global user.email "$GH_EMAIL"
                  git config --global user.name "$GH_NAME"
                  echo $GH_CLI_AUTH_TOKEN > gh.txt
                  gh auth login --with-token < gh.txt
                  yarn install
                  rm gh.txt
            - name: Bump Versioning
              id: bumpVersioning
              run: yarn run release
            - name: Package Extension
              id: packageExtension
              run: vsce package
            - name: Publish Extension
              id: publishExtension
              env:
                  VSCE_PAT: ${{secrets.VSCE_PAT}}
              run: yarn run deploy
            - name: Get Version Number
              id: version
              run: echo "::set-output name=VERSION::$(node -p -e "require('./package.json').version")"
            - name: Create GitHub Release
              id: createGitHubRelease
              run: gh release create ${{steps.version.outputs.VERSION}} -F CHANGELOG.md ./omnihive-server-manager-${{steps.version.outputs.VERSION}}.vsix
            - name: Push Version Bump
              id: pushVersionBump
              run: git push --follow-tags origin master
