extends: "@istanbuljs/nyc-config-typescript"
all: true
check-coverage: true
reporter:
    - "html"
    - "text"
    - "text-summary"
include:
    - "src/server/**/*"
exclude:
    - "**/node_modules/**"
    - "**/tests/**"
    - "**/*.js"
    - "**/*.d.ts"
    - "**/dist/**"
    - "src/server/**/interfaces/**"
    - "src/server/**/enums/**"
    - "build*.ts"
