name: OmniHive Web/Docs

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: PNPM Install
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.17.0
                  run_install: |
                      - recursive: true
            - name: Build Docusaurus
              run: pnpm run build:docs
            - name: Build Docker Images
              run: docker build . -f ./docker-docs.dockerfile --tag omnihive-web
            - name: GitHub Action for DigitalOcean - doctl
              uses: digitalocean/action-doctl@v2.1.0
              with:
                  token: ${{ secrets.DO_ACCESS_TOKEN }}
            - name: Login to doctl
              run: doctl registry login
            - name: Docker Tag
              run: docker tag omnihive-web registry.digitalocean.com/withonevision/omnihive-web
            - name: Push to Docker Registry
              run: docker push registry.digitalocean.com/withonevision/omnihive-web
            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 44331a93-78d1-4e11-8113-c46b723e5a71
            - name: Restart K8 deployment
              run: kubectl rollout restart deployment omnihive-web
