name: OmniHive VS Code Extension

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v2
            - name: PNPM Install
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.17.0
                  run_install: |
                      - recursive: true
            - name: Run Prerequisites
              env:
                  GH_CLI_AUTH_TOKEN: ${{secrets.GH_CLI_AUTH_TOKEN}}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
              id: runPrerequisites
              run: |
                  npm i -g vsce
                  git config --global user.email "$GH_EMAIL"
                  git config --global user.name "$GH_NAME"
                  echo $GH_CLI_AUTH_TOKEN > gh.txt
                  gh auth login --with-token < gh.txt
                  rm gh.txt
            - name: Package and Publish Extension
              id: packageExtension
              env:
                  VSCE_PAT: ${{secrets.VSCE_PAT}}
              run: |
                  cd src/other/omnihive-vscode-extension
                  vsce package
                  pnpm run deploy
